"""
SATYA — Google Fact Check Tools API Scraper
============================================
Fetches real Indian fact-check data and saves to CSV for fine-tuning.

Usage:
    set GOOGLE_FACTCHECK_API_KEY=your_key_here
    python ml/data/scrape_factcheck_api.py

Output: ml/data/regional_factchecks.csv
"""

import os
import sys
import csv
import json
import time
import hashlib
import random
from pathlib import Path
from datetime import datetime

try:
    import requests
except ImportError:
    print("ERROR: 'requests' not installed. Run: pip install requests pandas tqdm")
    sys.exit(1)
try:
    import pandas as pd
except ImportError:
    print("ERROR: 'pandas' not installed. Run: pip install requests pandas tqdm")
    sys.exit(1)
try:
    from tqdm import tqdm
except ImportError:
    print("ERROR: 'tqdm' not installed. Run: pip install requests pandas tqdm")
    sys.exit(1)

# Fix Windows console encoding for emoji/unicode
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# ─── Configuration ──────────────────────────────────────────────────────

API_ENDPOINT = "https://factchecktools.googleapis.com/v1alpha1/claims:search"
MAX_PAGES_PER_QUERY = 200
REQUEST_DELAY_SEC = 0.1  # 100ms between requests
MAX_RETRIES = 5
INITIAL_BACKOFF_SEC = 1.0

OUTPUT_DIR = Path(__file__).parent
OUTPUT_FILE = OUTPUT_DIR / "regional_factchecks.csv"
MIN_REQUIRED_CLAIMS = 500

# Target Indian fact-check publishers
PUBLISHER_FILTERS = [
    "boomlive.in",
    "altnews.in",
    "factly.in",
    "vishvasnews.com",
    "thequint.com",
    "factcrescendo.com",
    "digiteye.in",
    "newsmeter.in",
]

# Unfiltered search queries for broader Indian content
SEARCH_QUERIES = [
    "India",
    "WhatsApp forward",
    "Modi",
    "election India",
    "Bollywood fake",
    "COVID India",
    "Hindu Muslim",
    "Pakistan fake news",
    "viral video India",
    "morphed image",
]

# ─── Rating normalization ───────────────────────────────────────────────

MANIPULATED_KEYWORDS = [
    "false", "misleading", "manipulated", "fake", "hoax", "distorted",
    "misrepresented", "out of context", "morphed", "edited", "doctored",
    "incorrect", "wrong", "untrue", "deceptive", "pants on fire", "mostly false",
    # Added: common fact-checker labels that were falling through
    "altered", "satire", "satirical", "old video", "old image", "old photo",
    "unrelated", "misattributed", "miscaptioned", "recycled", "clipped",
    "cropped", "selectively edited", "partly true", "fabricated",
    "imposter", "outdated", "not from", "not related", "no evidence",
    "no connection", "fasle",  # common typo in fact-checker ratings
]

SYNTHETIC_KEYWORDS = [
    "deepfake", "ai-generated", "ai generated", "synthetic",
    "generated by ai", "fabricated image", "fabricated video",
    "generated using ai", "made with ai", "synthetic media",
    "computer generated",
]

AUTHENTIC_KEYWORDS = [
    "true", "correct", "accurate", "verified", "confirmed",
]
AUTHENTIC_NEGATIVES = ["not", "un-", "mostly false", "untrue", "partly"]

INCONCLUSIVE_KEYWORDS = [
    "half", "mixture", "unverified", "disputed",
    "missing", "unproven", "hard to categorise", "hard to categorize",
    "understated", "exaggerated", "unsupported",
]


def normalize_rating(rating_text: str) -> str:
    """Map a fact-checker's rating to one of our 4 verdict categories."""
    if not rating_text:
        return "INCONCLUSIVE"

    lower = rating_text.lower().strip()

    # Skip numeric-only ratings (e.g. "1") — they're meaningless
    if lower.isdigit():
        return "INCONCLUSIVE"

    # Check SYNTHETIC first (most specific)
    for kw in SYNTHETIC_KEYWORDS:
        if kw in lower:
            return "LIKELY_SYNTHETIC"

    # Check AUTHENTIC (but exclude negated forms)
    for kw in AUTHENTIC_KEYWORDS:
        if kw in lower:
            has_negative = any(neg in lower for neg in AUTHENTIC_NEGATIVES)
            if not has_negative:
                return "LIKELY_AUTHENTIC"

    # Check MANIPULATED before INCONCLUSIVE — most ambiguous labels lean manipulated
    for kw in MANIPULATED_KEYWORDS:
        if kw in lower:
            return "LIKELY_MANIPULATED"

    # Check INCONCLUSIVE
    for kw in INCONCLUSIVE_KEYWORDS:
        if kw in lower:
            return "INCONCLUSIVE"

    # Default fallback
    print(f"  ⚠ Unknown rating, defaulting to INCONCLUSIVE: '{rating_text}'")
    return "INCONCLUSIVE"


# ─── API fetching ───────────────────────────────────────────────────────

def fetch_page(api_key: str, query: str, page_token: str = None,
               publisher_filter: str = None) -> dict | None:
    """Fetch a single page from the Fact Check API with retry logic."""
    params = {
        "key": api_key,
        "query": query,
        "languageCode": "en",
        "pageSize": 10,
    }
    if page_token:
        params["pageToken"] = page_token
    if publisher_filter:
        params["reviewPublisherSiteFilter"] = publisher_filter

    for attempt in range(MAX_RETRIES):
        try:
            resp = requests.get(API_ENDPOINT, params=params, timeout=30)

            if resp.status_code == 200:
                return resp.json()
            elif resp.status_code == 429:
                wait = INITIAL_BACKOFF_SEC * (2 ** attempt) + random.uniform(0, 1)
                print(f"  ⏳ Rate limited. Waiting {wait:.1f}s (attempt {attempt+1}/{MAX_RETRIES})")
                time.sleep(wait)
            elif resp.status_code >= 500:
                wait = INITIAL_BACKOFF_SEC * (2 ** attempt)
                print(f"  ⚠ Server error {resp.status_code}. Retrying in {wait:.1f}s")
                time.sleep(wait)
            else:
                print(f"  ✗ API error {resp.status_code}: {resp.text[:200]}")
                return None
        except requests.RequestException as e:
            wait = INITIAL_BACKOFF_SEC * (2 ** attempt)
            print(f"  ✗ Request failed: {e}. Retrying in {wait:.1f}s")
            time.sleep(wait)

    print(f"  ✗ Failed after {MAX_RETRIES} retries. Skipping this page.")
    return None


def extract_claims(api_response: dict) -> list[dict]:
    """Extract claim records from an API response."""
    claims = []
    for item in api_response.get("claims", []):
        claim_text = item.get("text", "").strip()
        if not claim_text:
            continue

        claimant = item.get("claimant", "")
        claim_date = item.get("claimDate", "")

        # Each claim can have multiple reviews; take the first one
        reviews = item.get("claimReview", [])
        if not reviews:
            continue

        review = reviews[0]
        rating = review.get("textualRating", "")
        publisher_name = review.get("publisher", {}).get("name", "")
        publisher_site = review.get("publisher", {}).get("site", "")
        review_url = review.get("url", "")
        review_title = review.get("title", "")
        review_date = review.get("reviewDate", "")
        language = review.get("languageCode", "en")

        claims.append({
            "claim_text": claim_text,
            "claimant": claimant,
            "claim_date": claim_date,
            "rating": rating,
            "rating_normalized": normalize_rating(rating),
            "publisher": publisher_name,
            "publisher_site": publisher_site,
            "review_url": review_url,
            "review_title": review_title,
            "review_date": review_date,
            "language": language,
        })

    return claims


def run_query(api_key: str, query: str, publisher_filter: str = None,
              seen_hashes: set = None, pbar: tqdm = None) -> list[dict]:
    """Run a paginated query and return deduplicated claims."""
    if seen_hashes is None:
        seen_hashes = set()

    all_claims = []
    page_token = None
    label = f"query='{query}'"
    if publisher_filter:
        label += f", publisher={publisher_filter}"

    for page_num in range(MAX_PAGES_PER_QUERY):
        data = fetch_page(api_key, query, page_token, publisher_filter)
        if data is None:
            break

        page_claims = extract_claims(data)
        if not page_claims:
            break

        # Deduplicate
        for claim in page_claims:
            h = hashlib.sha256(claim["claim_text"].encode()).hexdigest()
            if h not in seen_hashes:
                seen_hashes.add(h)
                all_claims.append(claim)
                if pbar is not None:
                    pbar.update(1)

        # Check for next page
        page_token = data.get("nextPageToken")
        if not page_token:
            break

        time.sleep(REQUEST_DELAY_SEC)

    return all_claims


# ─── Main ───────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("SATYA — Google Fact Check API Scraper")
    print("=" * 60)

    # Get API key
    api_key = os.environ.get("GOOGLE_FACTCHECK_API_KEY", "")
    if not api_key:
        print("ERROR: GOOGLE_FACTCHECK_API_KEY environment variable not set.")
        print("Run: set GOOGLE_FACTCHECK_API_KEY=your_key_here")
        sys.exit(1)

    # Verify API key works
    print("\n🔑 Verifying API key...")
    test = fetch_page(api_key, "India test")
    if test is None:
        print("ERROR: API key verification failed. Check your key.")
        sys.exit(1)
    print("✓ API key valid.\n")

    seen_hashes = set()
    all_claims = []

    # Calculate total queries for progress bar
    total_queries = len(PUBLISHER_FILTERS) + len(SEARCH_QUERIES)
    # Each publisher filter runs with a generic "India" query
    # Each search query runs without a publisher filter

    with tqdm(desc="Claims collected", unit=" claims") as pbar:
        # Phase 1: Publisher-filtered queries
        print("─── Phase 1: Publisher-filtered queries ───")
        for pub in PUBLISHER_FILTERS:
            print(f"  → Scraping {pub}...")
            claims = run_query(api_key, "claim", publisher_filter=pub,
                              seen_hashes=seen_hashes, pbar=pbar)
            all_claims.extend(claims)
            print(f"    Got {len(claims)} new claims (total: {len(all_claims)})")

            # Also try empty query for max coverage
            claims2 = run_query(api_key, "", publisher_filter=pub,
                               seen_hashes=seen_hashes, pbar=pbar)
            all_claims.extend(claims2)
            if claims2:
                print(f"    +{len(claims2)} from empty query (total: {len(all_claims)})")

        # Phase 2: Unfiltered topic queries
        print("\n─── Phase 2: Unfiltered topic queries ───")
        for query in SEARCH_QUERIES:
            print(f"  → Searching '{query}'...")
            claims = run_query(api_key, query, seen_hashes=seen_hashes, pbar=pbar)
            all_claims.extend(claims)
            print(f"    Got {len(claims)} new claims (total: {len(all_claims)})")

    # ─── Save to CSV ────────────────────────────────────────────────────
    print(f"\n{'=' * 60}")
    print(f"Total unique claims collected: {len(all_claims)}")

    if len(all_claims) < MIN_REQUIRED_CLAIMS:
        print(f"\n⚠ WARNING: Only {len(all_claims)} claims collected.")
        print(f"  Expected at least {MIN_REQUIRED_CLAIMS}.")
        print(f"  The fine-tuning quality may be insufficient.")
        print(f"  Consider adding more search queries or checking API quotas.")
        # Don't exit — save whatever we have

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    df = pd.DataFrame(all_claims)
    df.to_csv(OUTPUT_FILE, index=False, quoting=csv.QUOTE_ALL)
    print(f"\n✓ Saved to: {OUTPUT_FILE}")
    print(f"  Rows: {len(df)}")
    print(f"  Columns: {list(df.columns)}")

    # ─── Summary stats ──────────────────────────────────────────────────
    print(f"\n─── Rating Distribution ───")
    rating_dist = df["rating_normalized"].value_counts()
    for label, count in rating_dist.items():
        pct = count / len(df) * 100
        print(f"  {label}: {count} ({pct:.1f}%)")

    categories_present = rating_dist.index.tolist()
    if len(categories_present) < 3:
        print(f"\n⚠ WARNING: Only {len(categories_present)} categories present.")
        print(f"  Need at least 3 for balanced training.")

    print(f"\n─── Publisher Distribution ───")
    pub_dist = df["publisher"].value_counts().head(15)
    for pub, count in pub_dist.items():
        print(f"  {pub}: {count}")

    # ─── Sample rows ────────────────────────────────────────────────────
    print(f"\n─── Sample (5 random rows) ───")
    sample = df.sample(min(5, len(df)), random_state=42)
    for _, row in sample.iterrows():
        print(f"  Claim: {row['claim_text'][:80]}...")
        print(f"  Rating: {row['rating']} → {row['rating_normalized']}")
        print(f"  Publisher: {row['publisher']} ({row['publisher_site']})")
        print()

    # ─── Next steps ─────────────────────────────────────────────────────
    print("=" * 60)
    print("🧑 HUMAN ACTION REQUIRED")
    print("=" * 60)
    print("""
What you need to do:
  1. Open ml/data/regional_factchecks.csv and verify:
     - There are at least 500 rows
     - The claim_text column has real claims (not empty)
     - The rating_normalized column has values across all 4 categories
  2. Upload this CSV to Kaggle as a private dataset:
     a. Go to https://www.kaggle.com/datasets
     b. Click "New Dataset"
     c. Drag the CSV file in
     d. Title: "SATYA Regional Fact-Check Data"
     e. Visibility: Private (only your account needs access)
     f. Click "Create"
  3. In your Kaggle fine-tuning notebook, click "Add Data"
     → search for your private dataset → add it
  4. The dataset will be mounted at:
     /kaggle/input/satya-regional-fact-check-data/regional_factchecks.csv

What you need to tell me:
  - Confirmation the CSV has 500+ rows
  - Confirmation it's uploaded to Kaggle and mounted in the notebook
""")


if __name__ == "__main__":
    main()
