// File generated manually from Firebase console config.
// Normally generated by `flutterfire configure`.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android and iOS use the same web config for now.
  // When you run `flutterfire configure` with the Firebase CLI,
  // platform-specific configs will be generated automatically.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD62jIedjjuIqla68X1JfsEYLoHd-h4Dc',
    appId: '1:233451750399:web:3babc44374c03815381dca',
    messagingSenderId: '233451750399',
    projectId: 'satya-verdict-cache',
    storageBucket: 'satya-verdict-cache.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD62jIedjjuIqla68X1JfsEYLoHd-h4Dc',
    appId: '1:233451750399:web:3babc44374c03815381dca',
    messagingSenderId: '233451750399',
    projectId: 'satya-verdict-cache',
    storageBucket: 'satya-verdict-cache.firebasestorage.app',
    iosBundleId: 'com.satya.satya',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD62jIedjjuIqla68X1JfsEYLoHd-h4Dc',
    appId: '1:233451750399:web:3babc44374c03815381dca',
    messagingSenderId: '233451750399',
    projectId: 'satya-verdict-cache',
    storageBucket: 'satya-verdict-cache.firebasestorage.app',
    authDomain: 'satya-verdict-cache.firebaseapp.com',
  );
}
